service: alimenz

image: andresalatalima/alimenz

servers:
  web:
    hosts:
      - 49.12.36.132

proxy:
  ssl: true
  host: alimenz.com.br
  app_port: 3000

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - POSTGRES_PASSWORD
    - ALIMENZ_DATABASE_PASSWORD
    - KAMAL_REGISTRY_PASSWORD


ssh:
  user: root

volumes:
  - "./storage:/rails/storage"


accessories:
  db:
    image: postgres:15.3
    host: 49.12.36.132
    env:
      clear:
        POSTGRES_DB: alimenz_production
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
